version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dev-go-fiber-stack"
s3_bucket = "go-fiber-stack-s3-bucket"
s3_prefix = "dev"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = [
    "Region=ap-northeast-1",
    "Environment=dev",
    "ProjectName=xxxxxx",
    "DevDomain=dev-api.xxxxx.xxx",
    "ProdDomain=api.xxxxx.xxx",
    "CertificateArn=arn:aws:acm:ap-northeast-1:xxxx:certificate/xxxxxx",
    "HostedZoneId=Z0xxxxxxx",
    "VpcId=vpc-xxxxxxxxx",
    "SubnetIds=subnet-xxxxxxxxxxxx,subnet-xxxxxxxxxxxx",
    "RDS_SECRET_NAME=xxxxxxx",
]

[prod.deploy.parameters]
stack_name = "prod-go-fiber-stack"
s3_bucket = "go-fiber-stack-s3-bucket"
s3_prefix = "prod"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "Region=ap-northeast-1",
    "Environment=prod",
    "ProjectName=xxxxxx",
    "DevDomain=dev-api.xxxxx.xxx",
    "ProdDomain=api.xxxxx.xxx",
    "CertificateArn=arn:aws:acm:ap-northeast-1:xxxx:certificate/xxxxxx",
    "HostedZoneId=Z0xxxxxxx",
    "VpcId=vpc-xxxxxxxxx",
    "SubnetIds=subnet-xxxxxxxxxxxx,subnet-xxxxxxxxxxxx",
    "RDS_SECRET_NAME=xxxxxxx",
]